# Generated by Django 2.2.3 on 2021-10-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_registro', models.IntegerField(choices=[[0, 'CONSULTAS'], [1, 'RECLAMOS'], [2, 'SUGERENCIAS'], [3, 'FELICITACIONES']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion_partida', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to='tour')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to='departamento')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Direccion')),
            ],
        ),
    ]
