# Generated by Django 2.2.3 on 2021-10-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.IntegerField(choices=[[1, 'Administrador'], [2, 'Guardia'], [3, 'Recepcionista'], [4, 'Limpieza']])),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(max_length=10)),
                ('sexo', models.IntegerField(choices=[[1, 'Mujer'], [2, 'Hombre'], [3, 'No definido']])),
                ('pago', models.IntegerField(default=0)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
