# Generated by Django 2.2.3 on 2021-10-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proveedor', models.IntegerField(choices=[[1, 'Administrador'], [2, 'Guardia'], [3, 'Recepcionista'], [4, 'Limpieza']])),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=10)),
                ('pago', models.IntegerField(default=0)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
    ]
