# Generated by Django 2.2.3 on 2021-11-02 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('cant_dias', models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creacion ')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Departamento')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
