# Generated by Django 2.2.3 on 2021-11-09 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211102_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_llegada',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
