# Generated by Django 2.2.3 on 2021-11-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211109_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='departamento'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='departamento'),
        ),
    ]
