# Generated by Django 2.2.3 on 2021-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211114_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='direccion',
            new_name='locacion',
        ),
        migrations.AddField(
            model_name='departamento',
            name='estado',
            field=models.IntegerField(choices=[[0, 'MANTENCION'], [1, 'DISPONIBLE'], [2, 'OCUPADO']], default=3),
            preserve_default=False,
        ),
    ]
