# Generated by Django 2.2.3 on 2021-11-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211115_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='locacion',
        ),
    ]
