# Generated by Django 2.2.3 on 2021-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_departamento_locacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_llegada',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cant_dias',
            field=models.SmallIntegerField(verbose_name='Cantidad de dias a reservar'),
        ),
    ]
