# Generated by Django 2.2.3 on 2021-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211124_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='carro_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
