# Generated by Django 2.2.3 on 2021-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_carrito_carro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(choices=[[1, 'Pagado'], [2, 'No pagado'], [3, 'Cancelado']], default=1),
        ),
    ]
